spring:
  data:
    mongodb:
      uri: mongodb://468b6805eba9:27017/wallet?replicaSet=myrepl&retryWrites=true
allowed:
  origin: http://localhost:3000
#logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=ERROR

#logging.level.org.springframework=DEBUG