spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/wallet
allowed:
  origin: http://localhost:3000
#logging.level.org.springframework.web.servlet.handler.HandlerMappingIntrospector=ERROR

#logging.level.org.springframework=DEBUG